### ISSUE TITLE
Weakee dependency possible ES6 export issue

### ISSUE THREAD

**Issue by wrench7** [capaj/jspm-react#1]
I'm getting the following error when trying to run the project (after having followed the install instructions)

```
Potentially unhandled rejection [2] TypeError: Error evaluating github:capaj/jspm-hot-reloader@0.2.1/jspm-hot-reloader
Super expression must either be null or a function, not undefined
    at exports.default (http://localhost:9080/jspm_packages/npm/babel-runtime@5.8.25/helpers/inherits.js:7:11)
    at eval (http://localhost:9080/jspm_packages/github/capaj/jspm-hot-reloader@0.2.1/jspm-hot-reloader.js!eval:28:9)
    at System.register._export.execute (http://localhost:9080/jspm_packages/github/capaj/jspm-hot-reloader@0.2.1/jspm-hot-reloader.js!eval:180:9)
    at t (http://localhost:9080/jspm_packages/es6-module-loader.js:7:19798)
    at v (http://localhost:9080/jspm_packages/es6-module-loader.js:7:20180)
    at v (http://localhost:9080/jspm_packages/es6-module-loader.js:7:20027)
    at u (http://localhost:9080/jspm_packages/es6-module-loader.js:7:19856)
    at s (http://localhost:9080/jspm_packages/es6-module-loader.js:7:19737)
    at http://localhost:9080/jspm_packages/es6-module-loader.js:7:22064
    at O (http://localhost:9080/jspm_packages/es6-module-loader.js:7:7439)
```

There seems to be something up with the way the weakee dependency is being exported that's causing the inherits module to fail where it does.

Any help would be much appreciated.

**Comment by wrench7** [comment]
After running jspm install again (I renamed the config.js file that was in this repo before doing that) everything is working now. I'm still a little confused by how jspm chooses to honour existing maps in the config file when running jspm install again.

**Comment by capaj** [comment]
@wrench7 I get confused about that from time to time as well. When not sure, delete config and generate it again.

**Comment by wrench7** [comment]
I'm reopening this, as I'm getting the same issues now after the lastest updates in https://github.com/capaj/jspm-react/commit/1e0cccbfc8e184f38e37090632309e9dd7f702a1 and deleting the config.js file and jspm installing again now no longer fixes the issue. There's definitely something weird going on here, would appreciate if someone else can confirm that this library is working as expected for them?

**Comment by capaj** [comment]
I am using jspm-hot-reloader on several projects and I haven't encountered the issue yet. Which version of jspm are you using?

**Comment by wrench7** [comment]
Thanks for the steer in the right direction - I was using jspm 0.15.x and have upgraded to 0.16.14. Cloned and following the installation instructions again and that's sorted the error.

My first experiences with jspm have been a somewhat rocky one it has to be said... hopefully that's as a result of the speed with which it's moving along :-)
